# Generated by Django 3.0.8 on 2020-07-17 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STUDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField(max_length=11)),
                ('username', models.TextField(max_length=10)),
                ('passwd', models.TextField(max_length=20)),
                ('firstflag', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastflag', models.DateTimeField(default=django.utils.timezone.now)),
                ('superflag', models.DateTimeField(default=django.utils.timezone.now)),
                ('specialflag', models.DateTimeField(default=django.utils.timezone.now)),
                ('rank', models.IntegerField(default=1)),
                ('timesubtract', models.IntegerField(default=0)),
                ('timesubtract_last', models.IntegerField(default=0)),
                ('timesubtract_suprise', models.IntegerField(default=0)),
            ],
        ),
    ]
