# Generated by Django 3.1.2 on 2020-10-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studb',
            name='passwd',
            field=models.TextField(max_length=200),
        ),
    ]
